ENTRY           INSI1_  #type complete
TITLE           RecName: Full=Insulin-induced gene 1 protein; Short=INSIG-1;
                AltName: Full=Insulin-induced growth response protein CL-6;
                AltName: Full=Immediate-early protein CL-6;
ACCESSIONS      Q08755
SUMMARY         #length 259  #molecular-weight 28231  #checksum 2878
SEQUENCE
                 5        10        15        20        25        30
       1 M P R L H D H V W S Y P S A G A A R P Y S L P R G M I A A A
      31 L C P Q G P G A P E P E P A P R G Q R E G T A G F S A R P G
      61 S W H H D L V Q R S L V L F S F G V V L A L V L N L L Q I Q
      91 R N V T L F P D E V I A T I F S S A W W V P P C C G T A A A
     121 V V G L L Y P C I D S H L G E P H K F K R E W A S V M R C I
     151 A V F V G I N H A S A K L D F A N N V Q L S L T L A A L S L
     181 G L W W T F D R S R S G L G L G I T I A F L A T L I T Q F L
     211 V Y N G V Y Q Y T S P D F L Y I R S W L P C I F F S G G V T
     241 V G N I G R Q L A M G V P E K P H S D
///
